apiVersion: v2
appVersion: "3"
dependencies:
- condition: postgresql.deploy
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- condition: clickhouse.deploy
  name: clickhouse
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 7.x.x
- condition: valkey.deploy
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- condition: minio.deploy
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.x.x
description: Open source LLM engineering platform - LLM observability, metrics, evaluations,
  prompt management.
home: https://langfuse.com/
icon: https://langfuse.com/langfuse_logo.png
keywords:
- langfuse
- llm
- observability
- prompt management
- metrics
maintainers:
- email: contact@langfuse.com
  name: langfuse
  url: https://langfuse.com/
name: langfuse
sources:
- https://github.com/langfuse/langfuse
- https://github.com/langfuse/langfuse-k8s
type: application
version: 0.12.1
